#!/usr/bin/perl
# makefsdata-linux: regenerate httpd-fsdata.c for the Linux port.
#
# Same as the AVR makefsdata script, but emits "static const unsigned
# char" arrays (prog_char is typedef'd to unsigned char by the Linux
# pgmspace shim, so "prog_char" would work too; we use the shim's
# prog_char to stay consistent with the rest of the code).
#
# Run from contiki-linux/apps/ : ./makefsdata-linux

open(OUTPUT, "> httpd-fsdata.c");

chdir("httpd-fs");
open(FILES, "find . -type f |");

while($file = <FILES>) {

    if($file =~ /(CVS|~)/) {
        next;
    }

    chop($file);

    open(HEADER, "> /tmp/header") || die $!;
    print(HEADER "HTTP/1.0 200 OK\r\n");
    print(HEADER "Server: Contiki/pre-1.2 (http://contiki-os.org/)\r\n");
    if($file =~ /\.html$/) {
        print(HEADER "Content-type: text/html\r\n");
    } elsif($file =~ /\.gif$/) {
        print(HEADER "Content-type: image/gif\r\n");
    } elsif($file =~ /\.png$/) {
        print(HEADER "Content-type: image/png\r\n");
    } elsif($file =~ /\.jpg$/) {
        print(HEADER "Content-type: image/jpeg\r\n");
    } elsif($file =~ /\.css$/) {
        print(HEADER "Content-type: text/css\r\n");
    } elsif($file =~ /\.jar$/) {
        print(HEADER "Content-type: application/java-archive\r\n");
    } else {
        print(HEADER "Content-type: text/plain\r\n");
    }
    print(HEADER "\r\n");
    close(HEADER);

    unless($file =~ /\.plain$/ || $file =~ /cgi/) {
        system("cat /tmp/header $file > /tmp/file");
    } else {
        system("cp $file /tmp/file");
    }

    open(FILE, "/tmp/file");
    unlink("/tmp/file");
    unlink("/tmp/header");

    $file =~ s/\.//;
    $fvar = $file;
    $fvar =~ s-/-_-g;
    $fvar =~ s-\.-_-g;
    print(OUTPUT "static prog_char data".$fvar."[] = {\n");
    print(OUTPUT "\t/* $file */\n\t");
    for($j = 0; $j < length($file); $j++) {
        printf(OUTPUT "%#02x, ", unpack("C", substr($file, $j, 1)));
    }
    printf(OUTPUT "0,\n");

    $i = 0;
    while(read(FILE, $data, 1)) {
        if($i == 0) {
            print(OUTPUT "\t");
        }
        printf(OUTPUT "%#02x, ", unpack("C", $data));
        $i++;
        if($i == 10) {
            print(OUTPUT "\n");
            $i = 0;
        }
    }
    print(OUTPUT "};\n\n");
    close(FILE);
    push(@fvars, $fvar);
    push(@files, $file);
}

for($i = 0; $i < @fvars; $i++) {
    $file = $files[$i];
    $fvar = $fvars[$i];

    if($i == 0) {
        $prevfile = "NULL";
    } else {
        $prevfile = "file" . $fvars[$i - 1];
    }
    print(OUTPUT "struct httpd_fsdata_file file".$fvar."[] = {{$prevfile, data$fvar, ");
    print(OUTPUT "data$fvar + ". (length($file) + 1) .", ");
    print(OUTPUT "sizeof(data$fvar) - ". (length($file) + 1) ."}};\n\n");
}

print(OUTPUT "#define HTTPD_FS_ROOT file$fvars[$i - 1]\n\n");
print(OUTPUT "#define HTTPD_FS_NUMFILES $i");